name: microcosm

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: microcosm
      POSTGRES_DB: microcosm_development
      POSTGRES_PASSWORD: microcosm_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: nc -z localhost 5432
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - micronet

  memcached:
    image: memcached:1.6-alpine
    restart: always
    healthcheck:
      test: nc -z localhost 11211
    networks:
      - micronet

  # elastic-search:
  #   image: elasticsearch:7.13.1
  #   restart: always
  #   environment:
  #     discovery.type: single-node
  #   networks:
  #     - micronet

  api:
    build:
      context: ../microcosm
      dockerfile: dockerfiles/dev.Dockerfile
    depends_on:
      - db
      - memcached
      # - elastic-search
    healthcheck:
      test: nc -z localhost 80
    restart: always
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://microcosm:microcosm_password@db:5432/microcosm_development
      GOOSE_MIGRATION_DIR: ./db/migrations
    ports:
      - 127.0.0.1:8080:80
    networks:
      micronet:
        aliases:
          - microcosm.app
          - root.microcosm.app
          - dev1.microcosm.app
          - dev2.microcosm.app
          - localhost.microcosm.app
    develop:
      watch:
        - action: rebuild
          path: ../microcosm
          ignore:
            - .git

  web:
    build:
      context: ../microweb
      dockerfile: dockerfiles/dev.Dockerfile
    depends_on:
      - memcached
      - api
    # extra_hosts:
    #   - "dev1.microcosm.app:127.0.0.1"
    restart: always
    environment:
      API_SCHEME: http://
      MEMCACHE_HOST: memcached
    ports:
      - 127.0.0.1:80:80
    networks:
      - micronet
    develop:
      watch:
        - action: rebuild
          path: ../microweb/requirements.txt
        - action: sync
          path: ../microweb
          target: /app
          ignore:
            - .git

networks:
  micronet:

volumes:
  postgres-data:
    driver: local
